# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8599bb4b888365d0fda74b15e334791ad2d0612a1b8d0fc52475af39d3ef39d34faffb7392680bd71e467cf9b7a4f7db32e77bbcb83e42888bbd7fe52e7f5175

test:
  secret_key_base: 358199a29f81435691462e07f8707571748033530d5bf3b824e8e26fa8c75c9f1a7480ad971094118eb6a974288103b4dc55f5f9b32934daca725c4116f9e72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
